Fix identation

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -93,28 +93,28 @@ runs:
       shell: bash
       run: |
           echo "::error title=Error With Release::An unexpected error occured and Helm was unable to roll back successfully. Your changes may be partially deployed, and a manual rollback to a known working version via 'smile-cli app rollback' is recommended."
-        # Datadog API Event
-        # Define the event details
-        TITLE="[${{ inputs.short_environment }}] ${{ inputs.helm_release_name }} deployment rollback"
-        TEXT="${{ inputs.helm_release_name }} app rollback failed in ${{ inputs.short_environment }}."
-        TAGS=("environment:${{ inputs.short_environment }}" "service:${{ inputs.helm_release_name }}" "action:failed_rollback")
-        JSON_TAGS=$(printf '%s\n' "${TAGS[@]}" | jq -R . | jq -s .)
-        ALERT_TYPE="warning"
+          # Datadog API Event
+          # Define the event details
+          TITLE="[${{ inputs.short_environment }}] ${{ inputs.helm_release_name }} deployment rollback"
+          TEXT="${{ inputs.helm_release_name }} app rollback failed in ${{ inputs.short_environment }}."
+          TAGS=("environment:${{ inputs.short_environment }}" "service:${{ inputs.helm_release_name }}" "action:failed_rollback")
+          JSON_TAGS=$(printf '%s\n' "${TAGS[@]}" | jq -R . | jq -s .)
+          ALERT_TYPE="warning"
 
-        # Use curl to send the event to Datadog
-        RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X POST "https://api.datadoghq.com/api/v1/events" \
-             -H "Content-Type: application/json" \
-             -H "DD-API-KEY: ${DD_API_KEY}" \
-             -d "{
-                 \"title\": \"${TITLE}\",
-                 \"text\": \"${TEXT}\",
-                 \"tags\": ${JSON_TAGS},
-                 \"alert_type\": \"$ALERT_TYPE\"
-             }")
+          # Use curl to send the event to Datadog
+          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X POST "https://api.datadoghq.com/api/v1/events" \
+               -H "Content-Type: application/json" \
+               -H "DD-API-KEY: ${DD_API_KEY}" \
+               -d "{
+                   \"title\": \"${TITLE}\",
+                   \"text\": \"${TEXT}\",
+                   \"tags\": ${JSON_TAGS},
+                   \"alert_type\": \"$ALERT_TYPE\"
+               }")
 
-        if [ "$RESPONSE" -ne 202 ]; then
-            echo "Failed to send event to Datadog. API responded with status code: $RESPONSE"
-            exit 1
-        else
-            echo "Event sent to Datadog successfully."
-        fi
+          if [ "$RESPONSE" -ne 202 ]; then
+              echo "Failed to send event to Datadog. API responded with status code: $RESPONSE"
+              exit 1
+          else
+              echo "Event sent to Datadog successfully."
+          fi
